### ISSUE TITLE
Improve SARF configuration using Yaml variables

### ISSUE THREAD

**Issue by elchicodepython** [elchicodepython/SARF-Security-Assesment-and-Reporting-Framework#6]
SARF configuration could be simplified using variables.

Example:

```yaml
defaults:
    rabbitmq_queue_conf: &default_rabbitmq_conf
        type: "rabbit"
        connection_string: "tcp://"

    ftp_base_storage_backend: &ftp_storage_options
        type: ftp
        conf: &ftp_storage_conf
            user: "sarf"
            password: "sarf"
            host: "127.0.0.1"

    ftp_full_storage_backend: &ftp_full_storage_backend
        upload: *ftp_storage_options
        download: *ftp_storage_options
    
    crud:
        psql_connection: &psql_connection
            host: "127.0.0.1"
            port: 5432
            user: "sarf"
            password: "changeme"
            database: "sarf"

messages:
    tools:
        <<: *default_rabbitmq_conf
        queue: tools

    reports:
        <<: *default_rabbitmq_conf
        queue: reports

    notifications:
        <<: *default_rabbitmq_conf
        queue: notifications


storage_backend:
    tools:
        __baseconf: &__base_tools_storage_backend
            <<: *ftp_storage_conf
            basedir: /ftp/sarf/tools
        upload: *__base_tools_storage_backend
        download: *__base_tools_storage_backend

    reports:
        __baseconf: &__base_tools_storage_backend
            <<: *ftp_storage_conf
            basedir: /ftp/sarf/reports
        upload: *__base_tools_storage_backend
        download: *__base_tools_storage_backend


crud:
  companies:
    type: psql
    conf:
      <<: *psql_connection
      table: companies

  projects:
    type: psql
    conf:
      <<: *psql_connection
      table: companies

  reports:
    type: psql
    conf:
      <<: *psql_connection
      table: companies

  vulnerabilities:
    type: psql
    conf:
      <<: *psql_connection
      table: companies

  vuln_templates:
    type: psql
    conf:
      <<: *psql_connection
      table: companies
```
